import Foundation

/// Strings are written in Russian in the code and serve as keys; English comes from en.lproj/Localizable.strings
/// (generated by scripts/l10n/make_strings.py). The interface takes the localization macOS itself picks for the app
/// from the user's languages: the first of them FaceID has, English when it has none. So with the languages (uk, ru)
/// it is Russian, as the camera prompt from ru.lproj/InfoPlist.strings is, and the two never mix. A language chosen
/// for FaceID in System Settings → Language & Region → Applications wins.
public enum Localization {
    /// "ru" or "en" for this launch.
    public static let current: String = {
        // A development build without the bundle has no translations: the keys are Russian.
        guard Bundle.main.path(forResource: "en", ofType: "lproj") != nil else { return "ru" }
        forgetOldChoice()
        return Bundle.main.preferredLocalizations.first?.hasPrefix("ru") == true ? "ru" : "en"
    }()

    /// Versions before 1.1 picked Russian whenever it was among the Mac's languages and wrote that into the app's
    /// own language list; that entry would now look like a choice made in System Settings.
    private static func forgetOldChoice() {
        let defaults = UserDefaults.standard
        guard let id = Bundle.main.bundleIdentifier, let domain = defaults.persistentDomain(forName: id),
              let applied = domain["FaceIDAppliedLanguage"] as? String else { return }
        if domain["FaceIDLanguage"] == nil, let written = (domain["AppleLanguages"] as? [String])?.first, written.hasPrefix(applied) {
            defaults.removeObject(forKey: "AppleLanguages")
        }
        defaults.removeObject(forKey: "FaceIDAppliedLanguage")
        defaults.removeObject(forKey: "FaceIDLanguage")
    }

    /// Call as early as possible at launch.
    public static func apply() {
        _ = current
    }

    static func string(_ key: String) -> String {
        bundle?.localizedString(forKey: key, value: key, table: nil) ?? key
    }

    private static let bundle: Bundle? = {
        guard current != "ru", let path = Bundle.main.path(forResource: current, ofType: "lproj") else { return nil }
        return Bundle(path: path)
    }()
}

/// Localized string. `key` is the Russian text; `%@` placeholders are filled with `args`.
public func L(_ key: String, _ args: CVarArg...) -> String {
    let text = Localization.string(key)
    return args.isEmpty ? text : String(format: text, arguments: args)
}

/// A number in the interface language with the right plural form of the noun:
/// pluralize(n, "снимок", "снимка", "снимков", en: "shot", "shots").
public func pluralize(_ n: Int, _ one: String, _ few: String, _ many: String, en enOne: String, _ enMany: String) -> String {
    if Localization.current != "ru" {
        return "\(n) \(n == 1 ? enOne : enMany)"
    }
    let mod10 = n % 10, mod100 = n % 100
    let word: String
    if mod10 == 1 && mod100 != 11 {
        word = one
    } else if (2...4).contains(mod10) && !(12...14).contains(mod100) {
        word = few
    } else {
        word = many
    }
    return "\(n) \(word)"
}
